applications:
    pattern:  /
    defaults: { _controller: "ApplicationCertificatsBundle:CertificatsApplis:index" }

applications_show:
    pattern:  /{id}/show
    defaults: { _controller: "ApplicationCertificatsBundle:CertificatsApplis:show" }

applications_new:
    pattern:  /new
    defaults: { _controller: "ApplicationCertificatsBundle:CertificatsApplis:new" }

applications_create:
    pattern:  /create
    defaults: { _controller: "ApplicationCertificatsBundle:CertificatsApplis:create" }
    requirements: { _method: post }

#applications_edit:
#    pattern:  /{id}/edit
#    defaults: { _controller: "ApplicationCertificatsBundle:CertificatsApplis:edit" }

applications_update:
    pattern:  /{id}/update
    defaults: { _controller: "ApplicationCertificatsBundle:CertificatsApplis:update" }
 #   requirements: { _method: post }

applications_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ApplicationCertificatsBundle:CertificatsApplis:delete" }
   # requirements: { _method: post }
