services:
   application.form.new.eservice:
        class: Application\CertificatsBundle\Form\EserviceContratStepsType
        tags:
            - { name: form.type, alias: eservice }

   application.form.flow.new.eservice:
      class: Application\CertificatsBundle\Form\EserviceFlow
      parent: craue.form.flow
      scope: request 
      calls:
            - [ setFormType, [ @application.form.new.eservice ] ]
        
