_changements:
    resource: "@ApplicationChangementsBundle/Resources/config/routing/changements.yml"
    prefix:   /
    
_changements_comments:
    resource: "@ApplicationChangementsBundle/Resources/config/routing/changementscomments.yml"
    prefix:   /
    
_docchangements:
    resource: "@ApplicationChangementsBundle/Resources/config/routing/docchangements.yml"
    prefix:   /docchangements
    #prefix:   /admin/tag
