epost_categories_index:
    pattern:  /index
    defaults: { _controller: "ApplicationEpostBundle:Epost:indexAll" }



epost_tags_show:
    pattern:  /{tag}/
    defaults: { _controller: ApplicationEpostBundle:Epost:indexbytag }
    requirements:
        _method:  GET
        blog_id: \d+