epost_indexadmin:
    pattern:  /epostall
    defaults: { _controller: "ApplicationEpostBundle:Epost:indexAll" }

epost_indexstandard:
    pattern:  /
    defaults: { _controller: "ApplicationEpostBundle:Epost:standardblog" }
    
epost:
    pattern:  /postdashboard
    defaults: { _controller: "ApplicationEpostBundle:Epost:index" }

epost_indexserch:
    pattern:  /search
    defaults: { _controller: "ApplicationEpostBundle:Epost:indexsearch" }



epost_mesposts:
    pattern:  /mesposts
    defaults: { _controller: "ApplicationEpostBundle:Epost:indexmesposts" }

epost_propositions:
    pattern:  /propositions
    defaults: { _controller: "ApplicationEpostBundle:Epost:indexpropositions" }



        
epost_show:
    pattern:  /{id}/show
    defaults: { _controller: "ApplicationEpostBundle:Epost:show" }

epost_new:
    pattern:  /new
    defaults: { _controller: "ApplicationEpostBundle:Epost:new" }

epost_create:
    pattern:  /create
    defaults: { _controller: "ApplicationEpostBundle:Epost:create" }
    requirements: { _method: post }

epost_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ApplicationEpostBundle:Epost:edit" }

epost_update:
    pattern:  /{id}/update
    defaults: { _controller: "ApplicationEpostBundle:Epost:update" }
    requirements: { _method: post|put }

epost_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ApplicationEpostBundle:Epost:delete" }
    requirements: { _method: post|delete }

epost_showstandard:
    pattern:  /{blog_id}/{slug}/{comments}
    defaults: { _controller: ApplicationEpostBundle:Epost:show, comments: true }
    requirements:
        _method:  GET
        blog_id: \d+