<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */



namespace Application\CertificatsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use APY\DataGridBundle\Grid\Mapping as GRID;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */


/**
 * Changements
 *
 * @ORM\Table(name="eproduits")
 * @ORM\Entity(repositoryClass="Application\CertificatsBundle\Entity\EproduitRepository")
 */

class Eproduit
{
     /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
      * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

   /**
     * Get id
     *
     * @return integer 
     */
    
  
       /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=50, nullable=false)
     */
    private $name;
    
      /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=false)
     */
    private $description;

    
    
    
    
    public function getId()
    {
        return $this->id;
    }

   
    
     /**
      *  Set nom
     *
     * @param string $fileName
     * @return CertificatsCenter
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }
    
   
    /**
     * Constructor
     */
    public function __construct()
    {
 
    }
   
    /**
     * Set description
     *
     * @param string $description
     * @return Eservice
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

   
  
   
}