<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\CertificatsBundle\Entity;
use Doctrine\ORM\EntityRepository;



/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */


class EproduitRepository extends EntityRepository
{
    public function myFindAll($user_id) {
         
         $query = $this->createQueryBuilder('a')
    ->where('a.demandeur = :demandeur')
    ->setParameter('demandeur', $user_id)
    //->orderBy('p.price', 'ASC')
    ->getQuery();
      return $query;
       /*  return $this->createQueryBuilder('a')
                        ->leftJoin('a.idProjet', 'b')
                        ->leftJoin('a.idStatus', 'd')
                        ->leftJoin('a.demandeur', 'c')
                 ->add('orderBy', 'a.id DESC')
                        //   ->leftJoin('a.demandeur', 'c')
                        ->getQuery();*/
    }
}