<?php

namespace Application\MyNotesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotesRepository extends EntityRepository
{
    
    public function myFindAll() {
        return $this->createQueryBuilder('a')
                        ->getQuery();
                        
        //->getResult();
    }
    
      public function myFindaAll() {
        return $this->createQueryBuilder('a')
                        ->leftJoin('a.categories', 'b')
                        ->leftJoin('a.color', 'c')
                        ->getQuery();
    }
}
