<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\EpostBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class EpostCommentsRepository extends EntityRepository {

    public function myFind() {

        $query = $this->createQueryBuilder('a')
                ->leftJoin('a.proprietaire', 'b')
                ->leftJoin('a.categorie', 'c')
                ->leftJoin('a.idStatus', 'd')
                ->add('orderBy', 'a.id DESC')
                ->getQuery();
        return $query;
    }

    public function myFindAll($user_id) {

        $query = $this->createQueryBuilder('a')
                ->add('orderBy', 'a.id DESC')
                ->where('a.proprietaire = :proprietaire')
                ->leftJoin('a.proprietaire', 'b')
                ->leftJoin('a.categorie', 'c')
                ->leftJoin('a.idStatus', 'd')
                 ->setParameter('proprietaire', $user_id)
                ->getQuery();

        return $query;

        /* $query = $this->createQueryBuilder('a')
          ->add('orderBy', 'a.id DESC');

          if (isset($user_id)){
          $query=$query->where('a.proprietaire = :proprietaire')
          ->setParameter('proprietaire', $user_id);


          }
          ->getQuery(); */
        return $query;
    }
public function getCommentsForPost($postId, $approved = true)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.epost = :post_id')
                   ->addOrderBy('c.isComment')
                   ->addOrderBy('c.created')
                   ->setParameter('post_id', $postId);

        if (false === is_null($approved))
            $qb->andWhere('c.approved = :approved')
               ->setParameter('approved', $approved);

        return $qb->getQuery()
                  ->getResult();
    }
    public function myFindOtherAll($user_id) {

        $query = $this->createQueryBuilder('a')
                ->where('a.proprietaire <> :proprietaire')
                ->setParameter('proprietaire', $user_id)
                //  ->where('a.proprietaire.getId = :idproprietaire')
                 //       ->setParameter('idproprietaire', '2')
                   ->leftJoin('a.proprietaire', 'b')
                ->leftJoin('a.categorie', 'c')
                ->leftJoin('a.idStatus', 'd')
             
                ->add('orderBy', 'a.id DESC')
                ->getQuery();
        return $query;
    }

    /* public function myFindAll($user_id) {

      $query = $this->createQueryBuilder('a')
      ->where('a.demandeur = :demandeur')
      ->setParameter('demandeur', $user_id)
      //->orderBy('p.price', 'ASC')
      ->getQuery();
      return $query;

      } */
       public function FindGroupLastComments($limit=10,$group=null) {
           
         return $this->createQueryBuilder('p')
                
                //  ->add('orderBy', 'p.id DESC')
                 ->where('p.approved = 1')
                  ->leftJoin('p.epost', 'b')
                     ->leftJoin('b.proprietaire', 'c')
                 ->andWhere('c.idgroup = :groupid')
                 ->setParameter('groupid', $group)
                 ->orderby('p.updated', 'DESC')
                  ->setMaxResults($limit)
                        ->getQuery()
                 ->getResult();
     }
     
       public function FindLastComments($limit=10) {
           
         return $this->createQueryBuilder('p')
                
                //  ->add('orderBy', 'p.id DESC')
                 ->where('p.approved = 1')
                  ->leftJoin('p.epost', 'b')
                 ->orderby('p.updated', 'DESC')
                  ->setMaxResults($limit)
                        ->getQuery()
                 ->getResult();
     }
}