<?php

namespace Application\EpostBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpostNotesRepository extends EntityRepository {

    public function myFindAll() {
        return $this->createQueryBuilder('a')
                        ->getQuery();

        //->getResult();
    }

    public function getUserNotesForEpost($user_id,$epost_id)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.user = :userId')
                
                   ->addOrderBy('c.isComment')
                   ->addOrderBy('c.created')
                   ->setParameter('produit_id', $epost_id);

        if (false === is_null($approved))
            $qb->andWhere('c.approved = :approved')
               ->setParameter('approved', $approved);

        return $qb->getQuery()
                  ->getResult();
    }
   

}
