_epost:
    resource: "@ApplicationEpostBundle/Resources/config/routing/epost.yml"
    prefix:   /
    
_epost_comments:
    resource: "@ApplicationEpostBundle/Resources/config/routing/epostcomments.yml"
    prefix:   /epostcomments

_epost_categories:
    resource: "@ApplicationEpostBundle/Resources/config/routing/epostcategories.yml"
    prefix:   /ecategories

_epost_tags:
    resource: "@ApplicationEpostBundle/Resources/config/routing/eposttags.yml"
    prefix:   /etags
    
_epost_notes:
    resource: "@ApplicationEpostBundle/Resources/config/routing/epostnotes.yml"
    prefix:   /epostnotes  