parameters:
#    application_epost.example.class: Application\EpostBundle\Example

services:
    application_epost_twig_extension:
        class: Application\EpostBundle\Twig\Extensions\ApplicationEpostExtension
        tags:
            - { name: twig.extension }

